### ISSUE TITLE
Error while scanning Nexus IQ server for iqServer datasource.

### ISSUE THREAD

**Issue by richardimms** [sonatype-nexus-community/vscode-iq-plugin#180]
**Some details beforehand:**

Nexus Explorer DataSource: IQServer
Cannot provide Server URL or Application ID, but I have pulled the application ID straight from nexus server web UI.
Using UserID & Password generated from API Tokens.

**Issue:** 
Having set-up the Nexus IQ plugin locally I have issues while scanning the node_modules package with the IQ server as the data source. However, when switching to the community `ossindex` I am able to scan successfully. 

```
TRACE: Output Channel Log Level: INFO
TRACE: File logger Log Level: INFO
INFO: Log Level set to: INFO
INFO: Created new IQ Request Service at:
INFO: Starting to Munch on NpmDependencies dependencies
ERROR: missing componentIdentifier
ERROR: Nexus IQ extension failure
```
The above shows two things.
1) There is no Created Request Service URL
2) Missing Component Identifier.

WRT to the component identifier, having looked further into the logs I get the following.

```{"startTime":"2021-02-01T12:09:41.546Z","categoryName":"sonatypeIQ","data":["missing componentIdentifier",{"packageUrl":null,"hash":"06d0d7a5bbdcc058f370","componentIdentifier":null,"proprietary":false,"matchState":"unknown","pathnames":["pkg:npm\\%2540types\\lodash@4.14.168"],"displayName":"pkg:npm/%2540types/lodash@4.14.168","violations":[{"policyId":"65d04e0d1001485ebf14b9cfedd115a0","policyName":"Component-Unknown","policyThreatCategory":"OTHER","policyThreatLevel":2,"policyViolationId":"68293bcaf92b442dba82362c98755064","waived":false,"grandfathered":false,"constraints":[{"constraintId":"24a51ddaa2ed4086bc00b517bc374ee0","constraintName":"Unknown 3rd party component","conditions":[{"conditionSummary":"Match State is unknown","conditionReason":"Match state was 'Unknown'"},{"conditionSummary":"Proprietary is false","conditionReason":"Component does not contain proprietary packages"}]}]}]}],"level":{"level":40000,"levelStr":"ERROR","colour":"red"},"context":{},"pid":21944},```

**Comment by DarthHater** [comment]
Pretty easy to see what's going on (at least from our end!), however uh if you could share the following info (it's in the bug template):

- VS Code version
- Extension version
- IQ Server version (would be helpful!)

What's going on is the `"pkg:npm\\%2540types\\lodash@4.14.168"` is double encoded by the looks of it. `%40` is @ encoded, and `%2540` is %@ encoded, which is silly, and why it can't find anything! IQ Server version might help us out a lot here, because it could be IQ Server that's double encoding that value. 

In the meantime, we might be able to skip over stuff we can't locate (due to some issue like this) and indicate in the UI it wasn't able to find it (and to check the logs). 

Thanks for filing the issue, it's really appreciated!!!

**Comment by richardimms** [comment]
Hello, 

Thanks for the quick reply!

Vs Code Version: 1.52.1
Extension Version: 1.0.13
IQ Server Version: 104 Release

Let me know if there is anything else you'll need.

**Comment by hnagrasona** [comment]
There is a known issue on IQ Server versions earlier than v101 where encoded purls are not handled correctly. Upgrading to IQ version 101 or later should resolve this problem.

**Comment by DarthHater** [comment]
That is the truth! @richardimms if you can get your IQ Server upgraded to post 101, that would be awesome. Beyond that, maybe chime in a bit on how you would like the experience to be if you ran into this issue. Should we just say "couldn't scan that component" and mark it as such? I imagine someone will want to know that (so a) they can find this issue and upgrade, or b) tell us!)
